{
 "title": "Subsquid",
 "description": "Unofficial SubSquid dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "sqd_archive_chain_height_updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sqd_archive_chain_height_updates",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "Head updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(sqd_archive_archived_head_updates[5m])",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "process_cpu_system_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "Events per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sqd_archive_events_in_block", "legendFormat": "{{squid_chain}}" }
   ]
  },
  {
   "title": "sqd_archive_processed_events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sqd_archive_processed_events", "legendFormat": "{{squid_chain}}" }
   ]
  },
  {
   "title": "Head block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sqd_archive_head_block", "legendFormat": "{{squid_chain}}" }
   ]
  },
  {
   "title": "nodejs_heap_space_size_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "Nodejs_active_handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "nodejs_active_handles{type=\"Socket\"}",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "nodejs_version_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "{{squid_chain}}" }
   ]
  },
  {
   "title": "Number of archived events (including not yet commited to storage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(sqd_archive_processed_events[5m])",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "Best vs finalized chain height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sqd_archive_chain_best_height - sqd_archive_chain_last_finalized_height",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sqd_archive_block_archival_time_sec_bucket[5m])) by (le))",
     "legendFormat": "End to end block archival time"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sqd_archive_block_ingest_time_sec_bucket[5m])) by (le))",
     "legendFormat": "Block ingestion and decoding time"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sqd_arhive_grpc_request_time_bucket[5m])) by (le))",
     "legendFormat": "Distribution of the gRPC requests to the node endpoint"
    }
   ]
  }
 ]
}